# Generated by Django 3.1.5 on 2021-02-09 20:38

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(default='Creator', max_length=100)),
                ('bio', django_quill.fields.QuillField()),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', django_quill.fields.QuillField(blank=True, default='Biography forthcoming...')),
                ('website', models.URLField(blank=True, max_length=1000)),
                ('facebook', models.URLField(blank=True, max_length=1000)),
                ('twitter', models.URLField(blank=True, max_length=1000)),
                ('instagram', models.URLField(blank=True, max_length=1000)),
                ('imdb', models.URLField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('audioFile', models.FileField(upload_to='audio/')),
                ('image', models.ImageField(default='static/assets/artwork/thereordering_cassietaggart.jpg', upload_to='images/')),
                ('external_Link', models.URLField(max_length=1000)),
                ('date_Added', models.DateTimeField(auto_now_add=True)),
                ('performers', models.ManyToManyField(related_name='plays', to='main_app.Performer')),
            ],
            options={
                'ordering': ['-date_Added'],
            },
        ),
    ]
