# Generated by Django 3.1.7 on 2021-04-03 02:06

import cloudinary.models
import datetime
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(default='Creator', max_length=100)),
                ('bio', django_quill.fields.QuillField()),
                ('email', models.EmailField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', django_quill.fields.QuillField(blank=True)),
                ('imdb', models.URLField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1000)),
                ('audioFile', cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio')),
                ('image', cloudinary.models.CloudinaryField(default='sweetnectar_cassietaggart_default_qz039o.jpg', max_length=255, verbose_name='image')),
                ('release_Date', models.DateTimeField(default=datetime.datetime.now)),
                ('performers', models.ManyToManyField(related_name='plays', to='main_app.Performer')),
            ],
            options={
                'ordering': ['-release_Date'],
            },
        ),
    ]
