# Generated by Django 3.2.23 on 2025-10-27 00:16

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='description',
            field=django_quill.fields.QuillField(blank=True),
        ),
    ]
