# Generated by Django 3.1.5 on 2021-01-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='main_app.Actor'),
        ),
    ]
