# Generated by Django 3.1.5 on 2021-01-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210122_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=1000)),
                ('photo', models.ImageField(default='static/assets/icons/user-solid.svg', upload_to='images/')),
                ('email', models.URLField(max_length=1000)),
                ('website', models.URLField(blank=True, max_length=1000)),
                ('facebook', models.URLField(blank=True, max_length=1000)),
                ('twitter', models.URLField(blank=True, max_length=1000)),
                ('instagram', models.URLField(blank=True, max_length=1000)),
            ],
        ),
    ]
