# Generated by Django 3.1.5 on 2021-02-19 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210214_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='external_Link',
        ),
    ]
