# Generated by Django 3.1.7 on 2021-03-11 14:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210310_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='audioFile',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='play',
            name='image',
            field=cloudinary.models.CloudinaryField(default='sweetnectar_cassietaggart_default_qz039o.jpg', max_length=255, verbose_name='image'),
        ),
    ]
