# Generated by Django 3.2.23 on 2025-10-27 00:16

from django.db import migrations
from django_quill.fields import QuillField


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_play_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='description',
            field=QuillField(blank=True),
        ),
    ]
