# Generated by Django 3.1.5 on 2021-01-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
