# Generated by Django 3.1.7 on 2021-03-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210311_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='amazon_Link',
        ),
        migrations.RemoveField(
            model_name='play',
            name='apple_Link',
        ),
        migrations.RemoveField(
            model_name='play',
            name='google_Link',
        ),
        migrations.RemoveField(
            model_name='play',
            name='stitcher_Link',
        ),
    ]
