# Generated by Django 3.1.5 on 2021-02-22 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_play_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='release_Date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
