# Generated by Django 3.2.23 on 2025-10-27 01:17

from django.db import migrations, models
import django.utils.timezone
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20251026_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ['name'], 'verbose_name': 'Creator', 'verbose_name_plural': 'Creators'},
        ),
        migrations.AlterModelOptions(
            name='performer',
            options={'ordering': ['name'], 'verbose_name': 'Performer', 'verbose_name_plural': 'Performers'},
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['-release_Date'], 'verbose_name': 'Play', 'verbose_name_plural': 'Plays'},
        ),
        migrations.AddField(
            model_name='creator',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='performer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='play',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='play',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='performer',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='play',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='play',
            name='release_Date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, validators=[main_app.models.validate_future_date]),
        ),
        migrations.AddIndex(
            model_name='creator',
            index=models.Index(fields=['name'], name='main_app_cr_name_d64e67_idx'),
        ),
        migrations.AddIndex(
            model_name='performer',
            index=models.Index(fields=['name'], name='main_app_pe_name_b5ce73_idx'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['-release_Date'], name='main_app_pl_release_a9125f_idx'),
        ),
        migrations.AddIndex(
            model_name='play',
            index=models.Index(fields=['name'], name='main_app_pl_name_e01227_idx'),
        ),
    ]
