# Generated by Django 3.1.5 on 2021-02-22 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_play_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['-release_Date']},
        ),
        migrations.RemoveField(
            model_name='play',
            name='date_Added',
        ),
    ]
