# Generated by Django 3.1.5 on 2021-01-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210129_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='title',
            field=models.CharField(default='Creator', max_length=100),
        ),
    ]
