# Generated by Django 3.1.5 on 2021-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_creator_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='creator',
            name='bio',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
