# Generated by Django 3.1.7 on 2021-02-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210227_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='apple_Link',
            field=models.URLField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='play',
            name='google_Link',
            field=models.URLField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='play',
            name='spotify_Link',
            field=models.URLField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='play',
            name='stitcher_Link',
            field=models.URLField(default='#', max_length=1000),
        ),
    ]
