# Generated by Django 3.1.5 on 2021-02-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210201_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='creator',
            name='bio',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
