# Generated by Django 3.1.5 on 2021-02-01 21:01

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210201_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=django_quill.fields.QuillField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='creator',
            name='bio',
            field=django_quill.fields.QuillField(blank=True, max_length=5000),
        ),
    ]
