# Generated by Django 3.1.7 on 2021-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210228_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='apple_Link',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AlterField(
            model_name='play',
            name='google_Link',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AlterField(
            model_name='play',
            name='spotify_Link',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AlterField(
            model_name='play',
            name='stitcher_Link',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
